name: Documentation Deployment Actions

on:
  push:
    branches: [ gh-pages ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs

    - name: Build documentation
      run: mkdocs build

